# Generated by Django 3.0.3 on 2020-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200429_1610'),
        ('orders2', '0004_orderitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variation',
            field=models.ManyToManyField(to='products.Variation'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variation',
            field=models.ManyToManyField(to='products.Variation'),
        ),
    ]
