# Generated by Django 3.0.3 on 2020-05-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0008_orderitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variation',
        ),
    ]
