# Generated by Django 3.0.3 on 2020-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200429_1610'),
        ('orders2', '0009_remove_order_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_variation',
            field=models.ManyToManyField(related_name='color_variation', to='products.Variation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_variation',
            field=models.ManyToManyField(related_name='size_variation', to='products.Variation'),
        ),
    ]
