# Generated by Django 3.0.3 on 2020-05-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0010_auto_20200505_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color_variation',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_variation',
        ),
    ]
