# Generated by Django 3.0.3 on 2020-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_itemvariation_item'),
        ('orders2', '0011_auto_20200505_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(to='products.ItemVariation'),
        ),
    ]
