# Generated by Django 3.0.3 on 2020-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200512_2048'),
        ('orders2', '0013_remove_orderitem_item_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(to='products.ItemVariation'),
        ),
    ]
