# Generated by Django 3.0.3 on 2020-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruits and Vegetables', 'Fruits and Vegetables'), ('Electronics', 'Electronics'), ('Books', 'Books')], max_length=120, null=True),
        ),
    ]
