# Generated by Django 3.0.3 on 2020-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruits and Vegetables', 'Fruits and Vegetables'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books')], max_length=120, null=True),
        ),
    ]
