# Generated by Django 3.0.3 on 2020-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
