# Generated by Django 3.0.3 on 2020-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200428_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
