# Generated by Django 3.0.3 on 2020-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200428_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
