# Generated by Django 3.0.3 on 2020-04-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200428_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
