# Generated by Django 3.0.3 on 2020-04-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200429_0337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
