# Generated by Django 3.0.3 on 2020-04-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_variationmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-category']},
        ),
    ]
