# Generated by Django 3.0.3 on 2020-05-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200429_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
