# Generated by Django 3.0.3 on 2020-05-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_itemvariation_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariation',
            name='item',
        ),
    ]
