# Generated by Django 3.0.3 on 2020-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0013_remove_orderitem_item_variations'),
        ('products', '0022_remove_itemvariation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], default='size', max_length=120),
        ),
        migrations.AddField(
            model_name='variation',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ItemVariation',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='name',
        ),
    ]
